//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvenShare.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvenShare.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is a simple app to keep track of who ows whom how much when people put money together to do something. ähnelt.
        /// </summary>
        internal static string AboutPar1 {
            get {
                return ResourceManager.GetString("AboutPar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application was created in a personal attempt to learn building apps with Xamarin - the code is open source and can be viewed and taken from my GitHub repository. ähnelt.
        /// </summary>
        internal static string AboutPar2 {
            get {
                return ResourceManager.GetString("AboutPar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version 1.0.0 ähnelt.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add member ähnelt.
        /// </summary>
        internal static string BtnAddMember {
            get {
                return ResourceManager.GetString("BtnAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        internal static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete member ähnelt.
        /// </summary>
        internal static string BtnDeleteMember {
            get {
                return ResourceManager.GetString("BtnDeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to go back without saving any changes? ähnelt.
        /// </summary>
        internal static string DialogCancelEdit {
            get {
                return ResourceManager.GetString("DialogCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string DialogDelete {
            get {
                return ResourceManager.GetString("DialogDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete this expense? ähnelt.
        /// </summary>
        internal static string DialogDeleteExpense {
            get {
                return ResourceManager.GetString("DialogDeleteExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete this project member and all connected expenses? ähnelt.
        /// </summary>
        internal static string DialogDeleteMember {
            get {
                return ResourceManager.GetString("DialogDeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete this project? ähnelt.
        /// </summary>
        internal static string DialogDeleteProject {
            get {
                return ResourceManager.GetString("DialogDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back ähnelt.
        /// </summary>
        internal static string DialogGoBack {
            get {
                return ResourceManager.GetString("DialogGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter an amount ähnelt.
        /// </summary>
        internal static string ExpenseAmountInputPh {
            get {
                return ResourceManager.GetString("ExpenseAmountInputPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a member ähnelt.
        /// </summary>
        internal static string ExpenseMemberInputPh {
            get {
                return ResourceManager.GetString("ExpenseMemberInputPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a name ähnelt.
        /// </summary>
        internal static string ExpenseNameInputPh {
            get {
                return ResourceManager.GetString("ExpenseNameInputPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current project members: ähnelt.
        /// </summary>
        internal static string LabelCurrentMembers {
            get {
                return ResourceManager.GetString("LabelCurrentMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a new expense ähnelt.
        /// </summary>
        internal static string PageTitleAddExpense {
            get {
                return ResourceManager.GetString("PageTitleAddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a new project ähnelt.
        /// </summary>
        internal static string PageTitleAddProject {
            get {
                return ResourceManager.GetString("PageTitleAddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit an expense ähnelt.
        /// </summary>
        internal static string PageTitleEditExpense {
            get {
                return ResourceManager.GetString("PageTitleEditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit a project ähnelt.
        /// </summary>
        internal static string PageTitleEditProject {
            get {
                return ResourceManager.GetString("PageTitleEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expenses ähnelt.
        /// </summary>
        internal static string PageTitleExpenses {
            get {
                return ResourceManager.GetString("PageTitleExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        internal static string PageTitleProjects {
            get {
                return ResourceManager.GetString("PageTitleProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        internal static string PageTitleStatistics {
            get {
                return ResourceManager.GetString("PageTitleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a project member ähnelt.
        /// </summary>
        internal static string ProjectMemberInputPh {
            get {
                return ResourceManager.GetString("ProjectMemberInputPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a project title ähnelt.
        /// </summary>
        internal static string ProjectTitleInputPh {
            get {
                return ResourceManager.GetString("ProjectTitleInputPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ows  ähnelt.
        /// </summary>
        internal static string StatisticsFrag1 {
            get {
                return ResourceManager.GetString("StatisticsFrag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  to  ähnelt.
        /// </summary>
        internal static string StatisticsFrag2 {
            get {
                return ResourceManager.GetString("StatisticsFrag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Even shares ähnelt.
        /// </summary>
        internal static string StatisticsShares {
            get {
                return ResourceManager.GetString("StatisticsShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual spendings ähnelt.
        /// </summary>
        internal static string StatisticsSpendings {
            get {
                return ResourceManager.GetString("StatisticsSpendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        internal static string StatisticsTotal {
            get {
                return ResourceManager.GetString("StatisticsTotal", resourceCulture);
            }
        }
    }
}
